---
kind: pipeline
type: kubernetes
name: default
steps:
  # Generate docker image
  - name: docker-release
    image: plugins/docker
    settings:
      dockerfile: docker/Dockerfile
      context: docker
      repo: nox404/valheim
      auto_tag: yes
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  # Alerting
  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: mattermost_hook
    when:
      status:
      - failure
      - success
---
kind: signature
hmac: a383899a7ddc1417336bfbd6c09d66ede16834cd17fe3b62347232a6e3989aff

...
