---
kind: pipeline
type: kubernetes
name: default
steps:
  # Generate latest docker image
  - name: publish-latest
    image: plugins/docker
    settings:
      dockerfile: docker/Dockerfile
      repo: nox404/valheim
      tags:
        - "${DRONE_COMMIT_SHA:0:7}"
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - master
  # Generate tagged image
  - name: publish-release
    image: plugins/docker
    settings:
      dockerfile: docker/Dockerfile
      repo: nox404/valheim
      tags:
        - "${DRONE_TAG}"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      event:
        - tag
  # Alerting
  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: mattermost_hook
    when:
      status:
      - failure
      - success
---
kind: signature
hmac: 906ee1a3cc59ec431c3d202e06d0a5d9a3ddabef8768efdeb007c468564d727f

...
