apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valheim.fullname" . }}
  labels: {{- include "valheim.labels" . | nindent 4 }}
  {{- if .Values.secret }}
  {{- with .Values.secret.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
type: Opaque
data:
  password: {{ .Values.server.password | b64enc }}
